// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'API_KEY_1',
    appId: '1:21184883793:web:9f75288aeb195bb9075c70',
    messagingSenderId: '21184883793',
    projectId: 'pet-wellness-app-27be4',
    authDomain: 'pet-wellness-app-27be4.firebaseapp.com',
    storageBucket: 'pet-wellness-app-27be4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'API_KEY_2',
    appId: '1:21184883793:android:168f789a634c9a5a075c70',
    messagingSenderId: '21184883793',
    projectId: 'pet-wellness-app-27be4',
    storageBucket: 'pet-wellness-app-27be4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'API_KEY_3',
    appId: '1:21184883793:ios:d24228e39ab04044075c70',
    messagingSenderId: '21184883793',
    projectId: 'pet-wellness-app-27be4',
    storageBucket: 'pet-wellness-app-27be4.firebasestorage.app',
    iosBundleId: 'com.example.petWellnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'API_KEY_3',
    appId: '1:21184883793:ios:d24228e39ab04044075c70',
    messagingSenderId: '21184883793',
    projectId: 'pet-wellness-app-27be4',
    storageBucket: 'pet-wellness-app-27be4.firebasestorage.app',
    iosBundleId: 'com.example.petWellnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'API_KEY_1',
    appId: '1:21184883793:web:f0d6a96d355008e9075c70',
    messagingSenderId: '21184883793',
    projectId: 'pet-wellness-app-27be4',
    authDomain: 'pet-wellness-app-27be4.firebaseapp.com',
    storageBucket: 'pet-wellness-app-27be4.firebasestorage.app',
  );
}
